In [7]:
import numpy as np 

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3 ,10))

[3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(3 ,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(.5 , 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [10]:
np.arange(5 ,-4, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [11]:
np.arange(5 ,-4, -.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [14]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [16]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,4,2)) *5 

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [27]:
np.empty((2,3))

array([[4.65789755e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [29]:
a = np.eye(4)

In [30]:
a.shape

(4, 4)

In [31]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
a.size

16

In [34]:
a.ndim

2

In [36]:
a1 = np.random.randn(3,4)

In [37]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [38]:
import pandas as pd 

In [39]:
pd.DataFrame(a1)

0         1         2         3
0  0.891971 -1.153651 -0.057456  0.120469
1  0.097413  0.300175  0.759028  0.160313
2  0.356169  1.686957  1.277662 -0.223066

In [40]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [41]:
a1[1][1]

0.3001745329451818

In [45]:
a1[0:2 , 0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [46]:
a1[[0,1] , 0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [50]:
a1[[0,1] ,0:2]

array([[ 0.89197116, -1.15365104],
       [ 0.09741326,  0.30017453]])

In [51]:
a1

array([[ 0.89197116, -1.15365104, -0.05745584,  0.12046936],
       [ 0.09741326,  0.30017453,  0.75902832,  0.16031268],
       [ 0.35616933,  1.68695656,  1.2776625 , -0.22306634]])

In [52]:
a1[[1,2],3]

array([ 0.16031268, -0.22306634])

In [54]:
m1 = np.random.randint(1,3 , (3,3))

In [55]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [56]:
m2 = np.random.randint(2,4 , (3,3))

In [57]:
m2

array([[3, 2, 2],
       [3, 2, 3],
       [2, 3, 2]])

In [58]:
m1*m2

array([[6, 4, 2],
       [3, 4, 6],
       [2, 6, 2]])

In [59]:
m1@m2

array([[14, 11, 12],
       [13, 12, 12],
       [11,  9, 10]])

In [60]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [61]:
m2

array([[3, 2, 2],
       [3, 2, 3],
       [2, 3, 2]])

In [62]:
m1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [64]:
pow(m1 , 4)

array([[16, 16,  1],
       [ 1, 16, 16],
       [ 1, 16,  1]])

In [65]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [67]:
np.log10(m1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [68]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [69]:
m1**2


array([[4, 4, 1],
       [1, 4, 4],
       [1, 4, 1]])